# Utiliser l'image de base Nginx
FROM nginx:alpine

# Copier les fichiers de l'application frontend dans le répertoire approprié
COPY . /usr/share/nginx/html

# Exposer le port 80 pour le serveur web
EXPOSE 80
