steps:
  # Étape 1 : construire toutes les images
  - name: 'docker/compose:1.29.2'
    entrypoint: 'docker-compose'
    args:
      - '-f'
      - 'docker-compose.yml'
      - 'build'

  # Étape 2 : pousser toutes les images sur GCR
  - name: 'docker/compose:1.29.2'
    entrypoint: 'docker-compose'
    args:
      - '-f'
      - 'docker-compose.yml'
      - 'push'

images:
  - 'gcr.io/$PROJECT_ID/backend:latest'
  - 'gcr.io/$PROJECT_ID/frontend:latest'

options:
  logging: NONE
